# s3 deployment based on http://about.travis-ci.org/blog/2012-12-18-travis-artifacts/

# send to container based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2

install: true

language: java

#See https://issues.apache.org/jira/browse/FLINK-1072
matrix:
  include:
    - jdk: "openjdk7"
      env: PROFILE="-Dhadoop.profile=1 -Dscala-2.11"
    - jdk: "oraclejdk8"
      env: PROFILE="-Dhadoop.version=2.6.0 -Dscala-2.11 -Pinclude-tez -Dmaven.javadoc.skip=true"


git:
  depth: 100

notifications:

env:
    global: 
        # Global variable to avoid hanging travis builds when downloading cache archives.
        - MALLOC_ARENA_MAX=2

before_script:
   - "gem install --no-document --version 0.8.9 faraday "
   - "gem install --no-document travis-artifacts & "

# We run mvn and monitor its output. If there is no output for the specified number of seconds, we
# print the stack traces of all running Java processes.
script: "./tools/travis_mvn_watchdog.sh 300"

# deploy if the first job is successful; should be replaced by an after_all_success if travis finally supports it
after_success:
  - "./tools/deploy_to_maven.sh"
